pid_controller:
  ros__parameters:
    lateral_kp: 1.0200
    lateral_ki: 0.0000
    lateral_kd: 0.0000
    heading_kp: 1.5000
    heading_ki: 0.0000
    heading_kd: 0.0000
    max_linear_speed: 0.2000
    max_angular_speed: 0.4500
    max_angular_acceleration: 0.8000
    angular_command_deadband: 0.0200
