pid_controller:
  ros__parameters:
    lateral_kp: 1.8700
    lateral_ki: 0.0000
    lateral_kd: 0.0000
    heading_kp: 2.5000
    heading_ki: 0.0000
    heading_kd: 0.0000
    max_linear_speed: 0.1500
    max_angular_speed: 0.6000
    max_angular_acceleration: 0.8000
    angular_command_deadband: 0.0200
